<?php
return [
    'ONESIGNAL_AUTH_KEY' => env('ONESIGNAL_AUTH_KEY'),

    'ONESIGNAL_MANAGER_ID' => env('ONESIGNAL_MANAGER_ID'),
    'ONESIGNAL_MANAGER_KEY' => env('ONESIGNAL_MANAGER_KEY'),

    'ONESIGNAL_CUSTOMER_ID' => env('ONESIGNAL_CUSTOMER_ID'),
    'ONESIGNAL_CUSTOMER_KEY' => env('ONESIGNAL_CUSTOMER_KEY')
];