<?php

namespace App\Classes\MenuType;

use App\Classes\FieldInput\FieldInputPost;
use App\Classes\MenuTypeWithFieldInput;
use App\Classes\PostType;

class MenuTypePost extends MenuTypeWithFieldInput
{

    function get_id(): string
    {
        return 'post';
    }

    function get_title(): string
    {
        return __('Chi tiết nội dung');
    }

    function get_order(): int
    {
        return 0;
    }

    function get_group_id(): string
    {
        return 'content';
    }

    function get_icon(): string
    {
        return 'icon-book';
    }

    public function checkActive($item)
    {
        return parent::checkActive($item); // TODO: Change the autogenerated stub
    }

    public function getURL($item)
    {
        $options = $item->getOptions()->get('post_type');
        $options = collect($options);
        /** @var PostType $post_type */
        $post_type = $options->get('post_type');
        $posts = $options->get('posts');
        /** @var PostType $post */
        $post = $post_type::find($posts);
        return $post->getUrl();
    }

    protected function registerFieldInputs(): array
    {
        return [
            new FieldInputPost(
                'post_type',
                '',
                __('Trang nội dung'),
                '',
                1,
                FieldInputPost::buildConfigs(0)
                ),

        ];
    }
}